### ISSUE TITLE
Geckolib version support

### ISSUE THREAD

**Issue by VinceKezel** [SirJain0/PerfectPlushies#10]
Using the latest version of Geckolib 4.2.3 causes the mod to stop the game from loading since it requires Geckolib version exactly 4.2.1 ... as a quick fix for the server I edited the mod's _fabric.mod.json_ file where `"geckolib":"4.2.1"` to now read `"geckolib":">=4.2.1"`
With this fix the game loads and the plushies seem to work fine.

_Minecraft 1.20.1
Fabric 0.14.22 / Api 0.90.0
Perfect Plushies 1.3.0_

**Comment by SirJain0** [comment]
Updating your Perfect Plushies version should fix that since we fixed that in a newer version.
