### ISSUE TITLE
perfect plushies 1.6

### ISSUE THREAD

**Issue by n0t49a1n** [SirJain0/PerfectPlushies#11]
downloading v 1.6 from curse downloads 1.5 
making al the fabric 7  unplayable on a server
same client and server

![image](https://github.com/SirJain0/PerfectPlushies/assets/87333/b183d850-6f06-4af4-ba9e-ad61e5f6c5bd)

**Comment by Nyfaria** [comment]
This issue can't be resolved by us. This will be on AOF7 to update to our more recent versions.

**Comment by n0t49a1n** [comment]
what do u mean curseforge has wrong version .....   
1.5.0 = 1.5.0 file
1.6.0 = 1.5.0 file 
how is this a AOF issue   its your curseforge

**Comment by Nyfaria** [comment]
Because the fix to that issue is to upload a new Version.
Which we did.
The modpack would need to update to the new version for it to be fixed in the Modpack.
This is how things work.

**Comment by n0t49a1n** [comment]
ok awesome
